spring:
  data:
    mongodb:
      database: health_tech
      uri: mongodb+srv://kavindyarajapakshabcspgd:YLid69KODEIK7RaU@cluster0.ts8wj.mongodb.net/health_tech

  mail:
    host: smtp.gmail.com
    port: 587
    username: 'kavindyarajapaksha.bcspgd@gmail.com'
    password: '******'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api/notification-service

