spring:
  data:
    mongodb:
      database: health_tech
      uri: ${{MONGO_CONNECTION_STRING}}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api/notification-service

